version: '3.8'

services:
  postgres-db:
    image: postgres:14-alpine
    container_name: travel-postgres
    environment:
      POSTGRES_USER: traveluser
      POSTGRES_PASSWORD: travelpassword
      POSTGRES_DB: traveldb
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  redis-cache:
    image: redis:7-alpine
    container_name: travel-redis
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data 

volumes:
  postgres_data:
  redis_data: