spring.application.name=travel-app
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/travelapp
spring.datasource.username=traveluser
spring.datasource.password=travelpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
